Larger images support.
Attempt to overcome problem seen by Zvi:

	Error: unrecognized/unsupported machine ID (r1 = 0x00000e05).

	Available machine support:

	ffffffff        Generic OMAP4 (Flattened Device Tree)
	ffffffff        Generic AM33XX (Flattened Device Tree)
	ffffffff        Generic OMAP3-GP (Flattened Device Tree)
	ffffffff        Generic OMAP3 (Flattened Device Tree)
	0000060a        OMAP3 Beagle Board
	00000a9d        IGEP OMAP3 module
	00000928        IGEP v2 board
	00000ae7        OMAP4 Panda board

Most likely the problem caused by large image being decompressed and hurting
DTS in memory. So just move DTS into different address.